### PR TITLE
Cleanup string tokens

### PR DESCRIPTION
**Pull request by Razzeee**

### CODE REVIEW

**Comment by Razzeee** [comment]
@jmbockhorst I need a second opinion, if this would be a good thing to do or something we shouldn't do

**Comment by jmbockhorst** [comment]
What is the goal?

**Comment by Razzeee** [comment]
Goal is to slim down the c++ parsing as much as possible, it also seems to be good practice to not go overboard on tokens. As far as I know we don't really use the tokens inside the string. But I would also reach out to other projects using this.
I think it's also fairly easy to parse the string on your own, if you need to.

**Comment by Razzeee** [comment]
Okay, still seems to be WIP, current version takes us from 75 failed parses to 190 in the whole ecosystem test suite.

**Pull request closed without merging**
