### PR TITLE
fix: mark helper functions static, remove comments

### PR DESCRIPTION
**Pull request by amaanq**
Max noticed this conflict when compiling with another scanner with a `scan` function, marking them static fixes that

Thanks!

### CODE REVIEW

**Comment by razzeee** [comment]
Not sure which conflict, but I guess I'll trust you :)

**Comment by amaanq** [comment]
If you compile two parsers in a project where both have a scanner with a function `scan` then they will get linked to one of the parser's scan (for the original that is ok, but the other one will use another parser's scan which is bad)

**Comment by razzeee** [comment]
I guess you don't need a release, right?

**Comment by amaanq** [comment]
Not entirely, though anyone using crates.io @ the latest version (not git) will encouter this, you could do a patch bump maybe to 5.6.6 if you'd like

**Comment by razzeee** [comment]
Preparing in https://github.com/elm-tooling/tree-sitter-elm/pull/139

**Pull request merged**
